### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by hughsalimbeni** [georgekrasenov/icmnd#4]
I can get through an iteration or so, but then I get an OOM error.

**Comment by gkivanov** [comment]
Can you check whether the OOM you get is for RAM or for GPU memory?

I would assume that you got it for the GPU memory. In which case it removes the possibility of a memory leak in the ICMND class files as they do not actually use the GPU as all dequeue operations have only CPU kernels and thus run on the CPU and use the RAM. Unless you have disabled RAM page swapping of your OS,  in case you start running out of RAM, the OS will swap certain pages to disk and thus allocate more space. If you believe the issue is running out of RAM, you might want to reduce the capacity of the training and validation queues when initialising them. The capacity basically means the maximum number of batches you want to keep preloaded in memory.

Anyway, I also encountered similar issue with my models. It only occurs within the first few iterations when the model barely fits in the GPU memory. I believe it manages to push some of the tensors to RAM for the first iteration but then it fails for the second one and throws OOM.

Slightly reducing the size of the model always fixed the issue.

**Comment by hughsalimbeni** [comment]
to add more details: standard conv encoder and linear decoder, using a notebook with a K80

**Comment by gkivanov** [comment]
I do not experience OOM issues even with more complex encoder and decoder nets. From my perspective the problem must be on the model side not the dataset side.

**Comment by hughsalimbeni** [comment]
ok I found it. Too big layer at the end of the convolutions
